language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: false
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8.3

script:
  - mvn test --batch-mode
  - mvn fmt:check --batch-mode
  - mvn license:check --batch-mode
  - mvn notice:check --batch-mode
  - mvn javadoc:javadoc --batch-mode